#!/usr/bin/env python3
"""Render the two one-off production measurements without changing their data."""
import collections
import json
import pathlib
import re
import sys

run_id, latest_dir, server_dir, destination = sys.argv[1:]
lines = ["# Production Windows handle provenance", "", f"Measured by CI run [{run_id}](https://github.com/cortexkit/basal/actions/runs/{run_id}).", "", "Both images used the production release `ck-basal-worker.exe` (no worker", "deviation feature). The tool copied its bytes unchanged to a `ckdev-` name,", "launched the full confinement, enabled ProcessHandleTracing class 32 with", "16,384 slots before resume, and queried the process at its pre-input", "checkpoint after all startup checks. User-space symbols below are PDB-resolved,", "not nearest-export guesses. Kernel prefixes are retained verbatim and labelled", "kernel (unsymbolized). The three pipes were created by the parent and were", "the only entries in its explicit inherited-handle list.", "", "This is a one-off measurement, not the handle allowlist. Live startup checks", "continue to use the fixed per-image ceiling constants. An image change", "requires remeasurement. Creator chains identify initialization authority;", "they are not an exhaustive proof of every operation on the residual objects."]
for image, directory in [("windows-latest", pathlib.Path(latest_dir)), ("windows-2022", pathlib.Path(server_dir))]:
    report = json.loads((directory / "windows-handle-provenance.json").read_text(encoding="utf-8-sig"))
    if report["unresolved"]:
        raise SystemExit(f"STOP: {image} has unresolved creators: {report['unresolved']}")
    if report["total"] > 26 or report["total"] != len(report["handles"]):
        raise SystemExit(f"STOP: {image} has an invalid total")
    # Ceiling acceptance comes from the compiled live validator, not a second
    # table generated by this renderer from the same measurement.
    hash_text = (directory / "production-image-hash.txt").read_text(encoding="utf-8-sig")
    hashes = re.findall(r"\b[0-9A-Fa-f]{64}\b", hash_text)
    if len(hashes) != 1:
        raise SystemExit(f"expected one measured SHA-256 for {image}")
    groups = collections.defaultdict(list)
    for handle in report["handles"]:
        groups[(handle["type"], handle["access"])].append(handle)
    lines += ["", f"## {image}", "", f"Runner image: `{report.get('runner_image')}`; version: `{report.get('runner_version')}`.", f"[Unedited raw report](windows-handle-provenance-{image}.json).", f"Production image SHA-256: `{hashes[0].lower()}`.", f"Accepted ceiling profile: `{report['profile']}`. Total: **{report['total']}**.", "", "| Type | Granted access | Count | Creator chains |", "|---|---|---:|---|"]
    details = []
    for index, ((kind, access), handles) in enumerate(sorted(groups.items()), 1):
        chains = collections.Counter()
        for handle in handles:
            chain = handle.get("creator") or " → ".join(f"kernel (unsymbolized) @{frame['address']}" if frame["module"] == "kernel (unsymbolized)" else f"{frame['module']}!{frame['symbol']}+0x{frame['displacement']:x}" for frame in handle["stack"])
            if not chain:
                raise SystemExit(f"STOP: missing creator for {image} {kind}")
            chains[chain] += 1
        lines.append(f"| {kind} | `{access}` | {len(handles)} | C{index} |")
        details += ["", f"### C{index}: {kind} `{access}`", ""]
        for chain, count in sorted(chains.items()):
            details.append(f"- ×{count}: `{chain}`")
    lines += details
pathlib.Path(destination).write_text("\n".join(lines) + "\n")
print(f"Rendered two production inventories at {destination}")
