//! Observe loader-initiated ALPC connections using x64 hardware breakpoints.
//! No instruction bytes are changed and no message is generated by the observer.
use crate::native::*;
use serde_json::{Value, json};
use std::collections::BTreeMap;
use std::ffi::c_void;
use windows_sys::Win32::Foundation::*;
use windows_sys::Win32::System::Diagnostics::Debug::ReadProcessMemory;
use windows_sys::Win32::System::LibraryLoader::*;
use windows_sys::Win32::System::Threading::*;

#[link(name = "kernel32")]
unsafe extern "system" {
    fn GetThreadContext(thread: HANDLE, context: *mut c_void) -> i32;
    fn SetThreadContext(thread: HANDLE, context: *const c_void) -> i32;
}
#[repr(C, align(16))]
struct Context([u8; 1232]);
impl Context {
    fn new() -> Self {
        let mut context = Self([0; 1232]);
        context.0[48..52].copy_from_slice(&0x00100013u32.to_le_bytes());
        context
    }
    fn get(&self, offset: usize) -> u64 {
        u64::from_le_bytes(self.0[offset..offset + 8].try_into().unwrap())
    }
    fn set(&mut self, offset: usize, value: u64) {
        self.0[offset..offset + 8].copy_from_slice(&value.to_le_bytes());
    }
    fn resume(&mut self) {
        // RF suppresses the execution breakpoint for the resumed instruction,
        // preventing an immediate second stop at the same syscall entry.
        let flags = u32::from_le_bytes(self.0[68..72].try_into().unwrap()) | 0x10000;
        self.0[68..72].copy_from_slice(&flags.to_le_bytes());
        self.set(104, 0);
    }
}
unsafe fn read(process: HANDLE, address: usize, bytes: usize) -> Result<Vec<u8>> {
    unsafe {
        let mut buffer = vec![0; bytes];
        let mut returned = 0;
        check(
            ReadProcessMemory(
                process,
                address as *const c_void,
                buffer.as_mut_ptr().cast(),
                bytes,
                &mut returned,
            ),
            "ReadProcessMemory(connection)",
        )?;
        if returned != bytes {
            return Err("short connection memory read".into());
        }
        Ok(buffer)
    }
}
fn port_name(process: HANDLE, address: usize) -> Value {
    unsafe {
        let result = (|| {
            let header = read(process, address, 16)?;
            let length = u16::from_le_bytes(header[..2].try_into().unwrap()) as usize;
            let pointer = u64::from_le_bytes(header[8..16].try_into().unwrap()) as usize;
            if length > 4096 || length % 2 != 0 {
                return Err("invalid connection name length".into());
            }
            let text = read(process, pointer, length)?;
            let words: Vec<_> = text
                .chunks_exact(2)
                .map(|pair| u16::from_le_bytes([pair[0], pair[1]]))
                .collect();
            Ok::<_, String>(String::from_utf16_lossy(&words))
        })();
        result
            .map(|name| json!(name))
            .unwrap_or_else(|error| json!({"error":error}))
    }
}
struct Pending {
    output: usize,
    name: Value,
    api: &'static str,
}
pub struct Connections {
    addresses: [usize; 2],
    pending: BTreeMap<u32, Pending>,
    pub events: Vec<Value>,
}
impl Connections {
    pub fn new(remote_base: usize) -> Result<Self> {
        unsafe {
            let local = GetModuleHandleW(wide("ntdll.dll").as_ptr());
            let mut addresses = [0; 2];
            for (index, name) in [c"NtConnectPort", c"NtAlpcConnectPort"].iter().enumerate() {
                let symbol = GetProcAddress(local, name.as_ptr().cast())
                    .ok_or("missing connection export")?;
                addresses[index] = remote_base + symbol as usize - local as usize;
            }
            Ok(Self {
                addresses,
                pending: BTreeMap::new(),
                events: Vec::new(),
            })
        }
    }
    pub fn arm(&mut self, tid: u32) -> Value {
        unsafe {
            let thread = OpenThread(THREAD_GET_CONTEXT | THREAD_SET_CONTEXT, 0, tid);
            if thread.is_null() {
                return json!({"tid":tid,"error":last("OpenThread(connection breakpoint)")});
            }
            let thread = Handle(thread);
            let mut context = Context::new();
            if GetThreadContext(thread.0, context.0.as_mut_ptr().cast()) == 0 {
                return json!({"tid":tid,"error":last("GetThreadContext")});
            }
            context.set(72, self.addresses[0] as u64);
            context.set(80, self.addresses[1] as u64);
            context.set(104, 0);
            context.set(112, 5);
            let ok = SetThreadContext(thread.0, context.0.as_ptr().cast()) != 0;
            json!({"tid":tid,"armed":ok,"error":if ok {0} else {GetLastError()},"NtConnectPort":self.addresses[0],"NtAlpcConnectPort":self.addresses[1]})
        }
    }
    pub fn hit(&mut self, process: HANDLE, tid: u32) -> Option<Value> {
        unsafe {
            let thread = OpenThread(THREAD_GET_CONTEXT | THREAD_SET_CONTEXT, 0, tid);
            if thread.is_null() {
                return None;
            }
            let thread = Handle(thread);
            let mut context = Context::new();
            if GetThreadContext(thread.0, context.0.as_mut_ptr().cast()) == 0 {
                return None;
            }
            let fired = context.get(104) & 7;
            let detail = if fired & 4 != 0 {
                let pending = self.pending.remove(&tid)?;
                let handle = read(process, pending.output, 8)
                    .map(|bytes| json!(u64::from_le_bytes(bytes.try_into().unwrap())))
                    .unwrap_or_else(|error| json!({"error":error}));
                context.set(88, 0);
                context.set(112, 5);
                json!({"phase":"return","api":pending.api,"name":pending.name,"NTSTATUS":hex(context.get(120) as u32),"handle":handle,"tid":tid})
            } else if fired & 3 != 0 {
                let api = if fired & 1 != 0 {
                    "NtConnectPort"
                } else {
                    "NtAlpcConnectPort"
                };
                let name = port_name(process, context.get(136) as usize);
                let output = context.get(128) as usize;
                let return_address = read(process, context.get(152) as usize, 8).ok()?;
                context.set(88, u64::from_le_bytes(return_address.try_into().unwrap()));
                context.set(112, 21);
                self.pending.insert(
                    tid,
                    Pending {
                        output,
                        name: name.clone(),
                        api,
                    },
                );
                json!({"phase":"entry","api":api,"name":name,"tid":tid})
            } else {
                return None;
            };
            context.resume();
            let ok = SetThreadContext(thread.0, context.0.as_ptr().cast()) != 0;
            self.events.push(detail.clone());
            Some(
                json!({"observation":detail,"resume_context_set":ok,"error":if ok {0} else {GetLastError()}}),
            )
        }
    }
}
